name: ParkourTopTen
main: io.github.steve4744.parkourtopten.ParkourTopTen
version: 4.2
api-version: 1.20
description: Plugin for Parkour to show top ten heads
author: steve4744 (originally based on TopTenHeads by tastybento)
depend: [Parkour]
commands:
    parkourtopten:
        aliases: [ptt]
        description: Parkour top ten command
        usage: "Usage: /ptt create (course) OR /ptt remove [all]"
permissions:
    parkourtopten.admin:
        description: can create and remove top ten displays
        default: op        
    